/**
 * Created by kh.levon98 on 13-Sep-16.
 */
import './helpers';

import angular from 'angular/index';
import 'jquery/dist/jquery.min';
import '/scripts/assists/jquery.form';
import 'tinymce/tinymce.min.js';
import moment from 'moment/min/moment.min.js';


// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our dependencies
import 'angular-animate/angular-animate.min';
import 'angular-touch/angular-touch.min';
import 'angular-cookies/angular-cookies.min';

import 'angular-ui-router/release/angular-ui-router.min';
import 'a0-angular-storage/dist/angular-storage.min';
import 'lodash/dist/lodash.min';
import 'restangular/dist/restangular.min';
import 'angular-bootstrap/ui-bootstrap.min';
import 'angular-ui-switch/angular-ui-switch.min';
import 'angular-ui-tinymce/src/tinymce';
import 'angular-ui-notification/dist/angular-ui-notification';
import 'ng-tags-input/ng-tags-input.min';

import 'app/components/wysiwyg/bootstrap-colorpicker-module'
import 'app/components/wysiwyg/angular-wysiwyg'


// Import our templates file (generated by Gulp)
import './config/app.templates';

// Import our app functionaity
import './services/index';
import './store/index';
import './components/index';
import './layout/index';
import './pages/index';
import './filters/index';

// Create and bootstrap application
const requires = [
  'ngAnimate',
  'ngTouch',
  'ngCookies',

  'ui.router',
  'angular-storage',
  'restangular',
  'templates',
  'ui.bootstrap',
  'app.services',
  'app.store',
  'app.components',
  'app.layout',
  'app.pages',
  'app.filters',
  'uiSwitch',
  'ngTagsInput',
  'wysiwyg.module',
  'ui-notification'
];

// Mount on window for testing
const app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

app.constant("moment", moment);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
